#!/usr/bin/env python3
"""Repository-wide file-by-file audit and completion report generator.

Generates:
- REPO_FILE_BY_FILE_ANALYSIS.csv
- REPO_FILE_BY_FILE_ANALYSIS.md
- REPO_WIDE_COMPLETION_REPORT.md
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parent
CSV_OUT = ROOT / "REPO_FILE_BY_FILE_ANALYSIS.csv"
MD_OUT = ROOT / "REPO_FILE_BY_FILE_ANALYSIS.md"
SUMMARY_OUT = ROOT / "REPO_WIDE_COMPLETION_REPORT.md"


LATEX_ARTIFACT_EXTS = {
    ".aux",
    ".log",
    ".toc",
    ".out",
    ".bbl",
    ".blg",
    ".fdb_latexmk",
    ".fls",
    ".synctex",
    ".gz",  # used for .synctex.gz
}


@dataclass
class AuditRow:
    path: str
    category: str
    risk: str
    action: str
    note: str


def is_hidden_or_git(path: Path) -> bool:
    parts = {p.lower() for p in path.parts}
    return ".git" in parts


def classify(path: Path, text: str | None) -> AuditRow:
    rel = path.relative_to(ROOT).as_posix()
    low = rel.lower()
    suffix = path.suffix.lower()

    # Defaults
    category = "Normal"
    risk = "Low"
    action = "Keep"
    note = "No immediate action required"

    if "/08_archive/" in low or low.startswith("useless/"):
        category = "Archive"
        risk = "Low"
        action = "Keep archived"
        note = "Historical/legacy content"

    if ".backup" in low or "_backup_" in low or "old_versions" in low:
        category = "Backup"
        risk = "Medium"
        action = "Archive/verify canonical source"
        note = "Multiple manuscript variants increase drift risk"

    if suffix in LATEX_ARTIFACT_EXTS or low.endswith(".synctex.gz"):
        category = "Build Artifact"
        risk = "Medium"
        action = "Ignore/remove from VCS"
        note = "Generated file; should not be source-of-truth"

    if path.name in {"main.tex", "papier.tex", "papier_fixed.tex"}:
        category = "Manuscript Variant"
        risk = "Medium"
        action = "Consolidate"
        note = "Keep one canonical manuscript and archive variants"

    if path.suffix.lower() == ".py":
        category = "Python Script"
        risk = "Low"
        action = "Keep/maintain"
        note = "Script source file"

    if text:
        if ("c:\\users\\" in text.lower() or "onedrive" in text.lower()) and suffix in {".py", ".md", ".txt", ".csv", ".sh", ".ps1"}:
            category = "Portability"
            risk = "Medium"
            action = "Replace absolute paths"
            note = "Contains machine-specific path reference"

        if any(tok in text for tok in ["TODO", "FIXME", "TBD", "PLACEHOLDER"]):
            if risk == "Low":
                risk = "Medium"
            if action == "Keep":
                action = "Review outstanding items"
            note = "Contains unresolved work markers"

    return AuditRow(rel, category, risk, action, note)


def read_text_if_small(path: Path, size_limit: int = 512_000) -> str | None:
    try:
        if path.stat().st_size > size_limit:
            return None
        # Read best-effort; ignore decode errors for mixed-content docs.
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return None


def iter_files() -> Iterable[Path]:
    for p in ROOT.rglob("*"):
        if p.is_file() and not is_hidden_or_git(p):
            yield p


def generate() -> tuple[list[AuditRow], dict[str, int], dict[str, int]]:
    rows: list[AuditRow] = []
    category_counts: dict[str, int] = {}
    risk_counts: dict[str, int] = {}

    for path in iter_files():
        text = None
        if path.suffix.lower() in {".py", ".md", ".txt", ".csv", ".tex", ".sh", ".ps1", ".yml", ".yaml", ".json", ".toml", ".ini"}:
            text = read_text_if_small(path)

        row = classify(path, text)
        rows.append(row)

        category_counts[row.category] = category_counts.get(row.category, 0) + 1
        risk_counts[row.risk] = risk_counts.get(row.risk, 0) + 1

    rows.sort(key=lambda r: (r.risk, r.category, r.path))
    return rows, category_counts, risk_counts


def write_csv(rows: list[AuditRow]) -> None:
    with CSV_OUT.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["path", "category", "risk", "action", "note"])
        for r in rows:
            writer.writerow([r.path, r.category, r.risk, r.action, r.note])


def write_md(rows: list[AuditRow], category_counts: dict[str, int], risk_counts: dict[str, int]) -> None:
    high = [r for r in rows if r.risk == "High"]
    medium = [r for r in rows if r.risk == "Medium"]

    lines: list[str] = []
    lines.append("# Repository File-by-File Analysis")
    lines.append("")
    lines.append("This report is auto-generated by `repo_audit.py`.")
    lines.append("")
    lines.append(f"- Total files analyzed: {len(rows)}")
    lines.append(f"- High risk files: {len(high)}")
    lines.append(f"- Medium risk files: {len(medium)}")
    lines.append("")

    lines.append("## Risk Summary")
    for risk in sorted(risk_counts):
        lines.append(f"- {risk}: {risk_counts[risk]}")
    lines.append("")

    lines.append("## Category Summary")
    for cat in sorted(category_counts):
        lines.append(f"- {cat}: {category_counts[cat]}")
    lines.append("")

    lines.append("## Medium/High Priority Files")
    lines.append("")
    lines.append("| File | Category | Risk | Action | Note |")
    lines.append("|---|---|---|---|---|")
    for r in rows:
        if r.risk in {"High", "Medium"}:
            lines.append(f"| `{r.path}` | {r.category} | {r.risk} | {r.action} | {r.note} |")
    lines.append("")

    lines.append("## Full File-by-File Index")
    lines.append("")
    lines.append("The complete index is in `REPO_FILE_BY_FILE_ANALYSIS.csv`.")

    MD_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_summary(rows: list[AuditRow], risk_counts: dict[str, int]) -> None:
    medium = [r for r in rows if r.risk == "Medium"]

    top_actions: dict[str, int] = {}
    for r in medium:
        top_actions[r.action] = top_actions.get(r.action, 0) + 1

    action_lines = sorted(top_actions.items(), key=lambda x: (-x[1], x[0]))

    lines: list[str] = []
    lines.append("# Repository-Wide Completion Report")
    lines.append("")
    lines.append("## Completed in This Pass")
    lines.append("- Added root `.gitignore` for Python, LaTeX artifacts, Node, IDE files.")
    lines.append("- Replaced hardcoded absolute paths in key scripts with repo-relative logic:")
    lines.append("  - `fix_citations.py`")
    lines.append("  - `fix_latex_issues.py`")
    lines.append("  - `MIT-SCIENCE-PAPER/Full project/01_Science/manuscript/fix_corruptions.py`")
    lines.append("- Generated repository-wide file-by-file analysis artifacts.")
    lines.append("")

    lines.append("## Current Risk Snapshot")
    for risk in sorted(risk_counts):
        lines.append(f"- {risk}: {risk_counts[risk]} files")
    lines.append("")

    lines.append("## Recommended Next Repository-Wide Completions")
    for action, count in action_lines[:8]:
        lines.append(f"- {action}: {count} files")
    lines.append("")

    lines.append("## Generated Outputs")
    lines.append("- `REPO_FILE_BY_FILE_ANALYSIS.csv`")
    lines.append("- `REPO_FILE_BY_FILE_ANALYSIS.md`")
    lines.append("- `REPO_WIDE_COMPLETION_REPORT.md`")

    SUMMARY_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    rows, category_counts, risk_counts = generate()
    write_csv(rows)
    write_md(rows, category_counts, risk_counts)
    write_summary(rows, risk_counts)
    print(f"Generated: {CSV_OUT.name}, {MD_OUT.name}, {SUMMARY_OUT.name}")
    print(f"Analyzed files: {len(rows)}")


if __name__ == "__main__":
    main()
