#!/usr/bin/env python3
"""
fetch_alerts.py
===============

Fetches RSS feeds (Google Alerts, Rigzone, etc.) and generates a daily
markdown digest in the news/ directory.

Usage:
    python automation/fetch_alerts.py                 # Use default alert_feeds.txt
    python automation/fetch_alerts.py --feeds my.txt  # Use custom feeds file
    python automation/fetch_alerts.py --dry-run       # Preview without writing

Reads:
    alert_feeds.txt   (repo root) — one RSS URL per line, # comments allowed
    news/.seen_entries.json       — cache of previously seen entry IDs

Writes:
    news/YYYY/MM/YYYY-MM-DD.md   — daily digest in markdown
    news/.seen_entries.json       — updated cache
"""

import argparse
import hashlib
import json
import logging
import re
import sys
from datetime import datetime, timezone
from html import unescape
from pathlib import Path

try:
    import feedparser
except ImportError:
    sys.exit("Missing dependency: pip install feedparser")

try:
    import requests
except ImportError:
    sys.exit("Missing dependency: pip install requests")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("fetch_alerts")

# ── Paths ────────────────────────────────────────────────────────────────────
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_FEEDS_FILE = Path(__file__).resolve().parent / "alert_feeds.txt"
NEWS_DIR = REPO_ROOT / "news"
SEEN_CACHE = NEWS_DIR / ".seen_entries.json"


def load_feeds(feeds_path: Path) -> list[str]:
    """Load RSS feed URLs from a text file (one per line, # comments allowed)."""
    if not feeds_path.exists():
        log.warning("Feeds file not found: %s", feeds_path)
        return []
    urls = []
    for line in feeds_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            urls.append(line)
    log.info("Loaded %d feed URLs from %s", len(urls), feeds_path.name)
    return urls


def load_seen_cache() -> set[str]:
    """Load the set of previously seen entry hashes."""
    if SEEN_CACHE.exists():
        data = json.loads(SEEN_CACHE.read_text(encoding="utf-8"))
        return set(data)
    return set()


def save_seen_cache(seen: set[str]) -> None:
    """Persist the seen entry hashes."""
    SEEN_CACHE.parent.mkdir(parents=True, exist_ok=True)
    # Keep only the most recent 10,000 entries to prevent unbounded growth
    trimmed = sorted(seen)[-10000:]
    SEEN_CACHE.write_text(
        json.dumps(trimmed, indent=2), encoding="utf-8"
    )


def entry_hash(entry) -> str:
    """Generate a unique hash for a feed entry."""
    key = (entry.get("link", "") + entry.get("title", "")).encode("utf-8")
    return hashlib.sha256(key).hexdigest()[:16]


def clean_html(raw: str) -> str:
    """Strip HTML tags and decode entities."""
    text = re.sub(r"<[^>]+>", "", raw)
    return unescape(text).strip()


def fetch_all_entries(urls: list[str]) -> list[dict]:
    """Fetch all entries from the given RSS feed URLs."""
    all_entries = []
    session = requests.Session()
    session.headers.update({"User-Agent": "PetroleumMarketResearch/1.0"})

    for url in urls:
        try:
            resp = session.get(url, timeout=15)
            resp.raise_for_status()
            feed = feedparser.parse(resp.text)
            feed_title = feed.feed.get("title", url)
            log.info("  %s — %d entries", feed_title, len(feed.entries))

            for entry in feed.entries:
                all_entries.append({
                    "feed": feed_title,
                    "title": clean_html(entry.get("title", "Untitled")),
                    "link": entry.get("link", ""),
                    "summary": clean_html(entry.get("summary", "")),
                    "published": entry.get("published", ""),
                    "hash": entry_hash(entry),
                })
        except requests.RequestException as exc:
            log.warning("  Failed to fetch %s: %s", url, exc)
        except Exception as exc:
            log.warning("  Error parsing %s: %s", url, exc)

    return all_entries


def generate_digest(entries: list[dict], today: str) -> str:
    """Generate a markdown digest from entries."""
    lines = [
        f"# Daily News Digest — {today}",
        "",
        f"> Auto-generated by `fetch_alerts.py` at {datetime.now(timezone.utc):%H:%M UTC}",
        f"> {len(entries)} new item(s) found.",
        "",
        "---",
        "",
    ]

    # Group by feed source
    by_feed: dict[str, list[dict]] = {}
    for entry in entries:
        by_feed.setdefault(entry["feed"], []).append(entry)

    for feed_name, feed_entries in sorted(by_feed.items()):
        lines.append(f"## {feed_name}")
        lines.append("")
        for e in feed_entries:
            title = e["title"] or "Untitled"
            link = e["link"]
            summary = e["summary"][:300] + "..." if len(e["summary"]) > 300 else e["summary"]

            if link:
                lines.append(f"### [{title}]({link})")
            else:
                lines.append(f"### {title}")
            if summary:
                lines.append(f"> {summary}")
            if e["published"]:
                lines.append(f"*Published: {e['published']}*")
            lines.append("")

    lines.append("---")
    lines.append(f"*Generated by [fetch_alerts.py](../automation/fetch_alerts.py)*")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Fetch RSS alerts and generate a daily news digest.",
    )
    parser.add_argument(
        "--feeds",
        type=Path,
        default=DEFAULT_FEEDS_FILE,
        help="Path to feeds file (default: alert_feeds.txt)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview digest without writing files",
    )
    args = parser.parse_args()

    log.info("Petroleum Engineering News Digest Generator")
    log.info("=" * 60)

    # Load feeds
    urls = load_feeds(args.feeds)
    if not urls:
        log.warning("No feed URLs found. Create alert_feeds.txt with RSS URLs.")
        log.warning("See NEWS_MONITORING_SETUP.md for instructions.")
        return

    # Fetch entries
    log.info("Fetching %d feeds...", len(urls))
    all_entries = fetch_all_entries(urls)
    log.info("Total entries fetched: %d", len(all_entries))

    # Filter out already-seen entries
    seen = load_seen_cache()
    new_entries = [e for e in all_entries if e["hash"] not in seen]
    log.info("New entries (not seen before): %d", len(new_entries))

    if not new_entries:
        log.info("No new entries. Nothing to write.")
        return

    # Generate digest
    today = datetime.now().strftime("%Y-%m-%d")
    digest = generate_digest(new_entries, today)

    if args.dry_run:
        print("\n[DRY RUN] Digest preview:\n")
        print(digest)
        return

    # Write digest file
    year = datetime.now().strftime("%Y")
    month = datetime.now().strftime("%m")
    out_dir = NEWS_DIR / year / month
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{today}.md"

    # Append if file already exists (multiple runs per day)
    if out_file.exists():
        existing = out_file.read_text(encoding="utf-8")
        digest = existing + "\n\n---\n\n" + digest

    out_file.write_text(digest, encoding="utf-8")
    log.info("Wrote digest: %s", out_file.relative_to(REPO_ROOT))

    # Update seen cache
    for e in new_entries:
        seen.add(e["hash"])
    save_seen_cache(seen)
    log.info("Updated seen cache (%d total entries).", len(seen))

    log.info("Done.")


if __name__ == "__main__":
    main()
