#!/usr/bin/env python3
"""
preprocess-anpg-data.py
=======================

Pre-processes anpg-local-content-full-data.md to:
  1. Extract KPIs and write kpi-values.tex (\renewcommand overrides)
  2. Print a structural summary of the Markdown file

Usage:
    python preprocess-anpg-data.py

Reads:  anpg-local-content-full-data.md  (same directory)
Writes: kpi-values.tex                   (same directory)

The main LaTeX template (anpg-local-content-full-data.tex) auto-loads
kpi-values.tex via \IfFileExists so running this script is optional
but recommended for accurate KPI values.
"""

import re
import sys
from pathlib import Path
from datetime import datetime


# ── Helpers ──────────────────────────────────────────────────────────────

def fmt_latex(n: int | str) -> str:
    """Format a number with LaTeX thin-space thousands separators."""
    s = str(n).replace(",", "").strip()
    if not s.isdigit():
        return s
    # Insert \, every 3 digits from the right
    parts: list[str] = []
    while len(s) > 3:
        parts.append(s[-3:])
        s = s[:-3]
    parts.append(s)
    return "\\,".join(reversed(parts))


def parse_int(raw: str) -> int:
    """Parse a possibly comma-separated number string to int."""
    return int(raw.replace(",", "").replace(".", "").strip())


# ── KPI Extraction ───────────────────────────────────────────────────────

def extract_kpis(md: str) -> dict:
    """Extract all reportable KPIs from the Markdown text."""
    kpis: dict = {}

    # ── Registration pipeline ──
    m = re.search(r"Empresas Registadas.*?\*\*(\d[\d,]+)\*\*", md)
    if m:
        kpis["registered"] = parse_int(m.group(1))

    m = re.search(r"Empresas Visitadas.*?\*\*(\d[\d,]+)\*\*", md)
    if m:
        kpis["visited"] = parse_int(m.group(1))

    m = re.search(r"Empresas Certificadas.*?\*\*(\d[\d,]+)\*\*", md)
    if m:
        kpis["certified"] = parse_int(m.group(1))

    # ── Total in database ──
    m = re.search(r"\|\s*\*\*Total\*\*\s*\|\s*\*\*(\d[\d,]+)\*\*\s*\|", md)
    if m:
        kpis["total_db"] = parse_int(m.group(1))

    # ── Company types ──
    for code in ("SCA", "SE", "SCDA"):
        m = re.search(
            rf"\|\s*\*\*{code}\*\*\s*\|[^|]+\|\s*([\d,]+)\s*\|", md
        )
        if m:
            kpis[f"type_{code}"] = parse_int(m.group(1))

    # ── Status breakdown ──
    status_map: dict[str, int] = {}
    for m in re.finditer(
        r"\|\s*(Certificado|Aprovado \(Internacional\)|Aprovado|"
        r"Condicionado|Recusado|Pré Triagem|Triagem|"
        r"Em Certificação[^|]*)\s*\|\s*([\d,]+)\s*\|",
        md,
    ):
        label = m.group(1).strip()
        status_map[label] = parse_int(m.group(2))
    if status_map:
        kpis["status_counts"] = status_map

    # ── Category Summary Matrix → total mappings ──
    m = re.search(
        r"\|\s*\*\*TOTAL\*\*\s*\|[^|]*\|[^|]*\|\s*\*\*(\d[\d,]+)\*\*\s*\|",
        md,
    )
    if m:
        kpis["total_mappings"] = parse_int(m.group(1))

    # ── Nationalities ──
    nationalities: dict[str, int] = {}
    countries = (
        "Angola", "United Kingdom", "United States", "France",
        "United Arab Emirates", "Portugal", "South Africa", "Italy",
        "Norway", "Netherlands", "Nigeria", "India", "China", "Brazil",
    )
    for country in countries:
        m = re.search(
            rf"\|\s*{re.escape(country)}\s*\|\s*([\d,]+)\s*\|", md
        )
        if m:
            nationalities[country] = parse_int(m.group(1))
    if nationalities:
        kpis["nationalities"] = nationalities

    # ── Heading counts ──
    kpis["h2_count"] = len(re.findall(r"^## ", md, re.MULTILINE))
    kpis["h3_count"] = len(re.findall(r"^### ", md, re.MULTILINE))
    kpis["h4_count"] = len(re.findall(r"^#### ", md, re.MULTILINE))

    return kpis


# ── LaTeX Generation ─────────────────────────────────────────────────────

def generate_kpi_tex(kpis: dict) -> str:
    """Produce kpi-values.tex content with \\renewcommand overrides."""
    lines = [
        "% ──────────────────────────────────────────────────────────────",
        "% kpi-values.tex — auto-generated by preprocess-anpg-data.py",
        f"% Generated: {datetime.now():%Y-%m-%d %H:%M}",
        "% Re-run:  python preprocess-anpg-data.py",
        "% ──────────────────────────────────────────────────────────────",
        "",
    ]

    def cmd(name: str, value) -> str:
        return f"\\renewcommand{{\\{name}}}{{{fmt_latex(value)}}}"

    # Registration pipeline
    if "registered" in kpis:
        lines.append(cmd("kpiRegistered", kpis["registered"]))
    if "visited" in kpis:
        lines.append(cmd("kpiVisited", kpis["visited"]))
    if "certified" in kpis:
        lines.append(cmd("kpiCertified", kpis["certified"]))
    if "total_db" in kpis:
        lines.append(cmd("kpiTotalDB", kpis["total_db"]))

    # Data volume
    if "total_mappings" in kpis:
        lines.append(cmd("kpiMappings", kpis["total_mappings"]))

    # Company types
    for code in ("SCA", "SE", "SCDA"):
        key = f"type_{code}"
        if key in kpis:
            lines.append(cmd(f"kpi{code}", kpis[key]))

    # Local content proxy
    if "nationalities" in kpis and "total_db" in kpis:
        angola = kpis["nationalities"].get("Angola", 0)
        total = kpis["total_db"]
        pct = angola / total * 100 if total else 0
        lines.append(cmd("kpiAngolan", angola))
        lines.append(
            f"\\renewcommand{{\\kpiAngolanPct}}{{{pct:.1f}\\,\\%}}"
        )
        lines.append(
            f"\\renewcommand{{\\kpiForeignPct}}{{{100-pct:.1f}\\,\\%}}"
        )

    if "certified" in kpis and "total_db" in kpis:
        cert_pct = kpis["certified"] / kpis["total_db"] * 100
        lines.append(
            f"\\renewcommand{{\\kpiCertifiedPct}}{{{cert_pct:.1f}\\,\\%}}"
        )

    # Top nationalities for charts
    nat_map = {
        "United Kingdom": "kpiUK",
        "United States": "kpiUS",
        "France": "kpiFR",
        "United Arab Emirates": "kpiUAE",
        "Portugal": "kpiPT",
    }
    nats = kpis.get("nationalities", {})
    for country, macro in nat_map.items():
        if country in nats:
            lines.append(cmd(macro, nats[country]))

    lines.append("")
    return "\n".join(lines) + "\n"


# ── Main ─────────────────────────────────────────────────────────────────

def main() -> None:
    md_path = Path("anpg-local-content-full-data.md")

    if not md_path.exists():
        print(f"ERROR: {md_path} not found.  Run from the project root.")
        sys.exit(1)

    print(f"Reading {md_path} ...")
    md = md_path.read_text(encoding="utf-8")
    total_lines = md.count("\n") + 1
    print(f"  {len(md):,} characters · {total_lines:,} lines")

    print("\nExtracting KPIs ...")
    kpis = extract_kpis(md)

    # ── Print summary ──
    print("\n╔══════════════════════════════════════════════════════════╗")
    print("║                    KPI SUMMARY                          ║")
    print("╚══════════════════════════════════════════════════════════╝")

    for key in sorted(kpis):
        val = kpis[key]
        if isinstance(val, dict):
            print(f"\n  {key}:")
            for k, v in sorted(val.items(), key=lambda x: -x[1] if isinstance(x[1], int) else x[0]):
                print(f"    {k:30s}  {v:>8,}" if isinstance(v, int) else f"    {k}: {v}")
        else:
            print(f"  {key:25s}  {val:>8,}" if isinstance(val, int) else f"  {key:25s}  {val}")

    print(f"\n  Heading structure:")
    print(f"    ## (chapters):    {kpis.get('h2_count', '?'):>5}")
    print(f"    ### (sections):   {kpis.get('h3_count', '?'):>5}")
    print(f"    #### (subsects):  {kpis.get('h4_count', '?'):>5}")

    # ── Write kpi-values.tex ──
    tex = generate_kpi_tex(kpis)
    out_path = Path("kpi-values.tex")
    out_path.write_text(tex, encoding="utf-8")
    print(f"\n✓ Wrote {out_path}  ({len(tex)} bytes)")
    print("  Include in LaTeX preamble:  \\IfFileExists{kpi-values.tex}{\\input{kpi-values.tex}}{}")
    print("  (already included in the template by default)")


if __name__ == "__main__":
    main()
